### ISSUE TITLE
How to make override properties work with "Properties"

### ISSUE THREAD

**Issue by azakordonets** [qatools/properties#27]
Hey guys, 

This lib looks really awesome and handy, but i don't quit understand how should be implemented reading from override.properties mechanism? Is it even possible? Would it be possible to add 2 annotations for each file, or anything else that i'm missing?

**Comment by lanwen** [comment]
Please clarify your use case. Don't understand it for now

**Comment by azakordonets** [comment]
Sorry about that. Let's say we have properties file that is in resource folder. It has for example : 
host=devhost.net
user=admin
password=admin

Now, to test same functionality on different environment, or even on localhost, i need to have override.properties file where i can override all , or only part of properties
host=localhost
user=andrew
password=test

So, to achieve this, i need to write a class ServerProperties, where i will instantiate 2 files - serverProperties, overrideProperties. And then login in getting parameter by name would be : 
if (overrideProperties has this param name) {
use overrideProperties param; 
else if (serverProperties has this param name) {
use serverProperties param 
} else {
throw no such propertie exception; } 

With your library i see that you read resource file using annotation. but how can i get override properties then?

**Comment by lanwen** [comment]
What is your native lang? We have complete manual in RU (translation to EN is planned)

**Comment by baev** [comment]
@azakordonets sorry for the delay

Since 1.6 you can use the following construction:

```
@Resource.Classpath({"server.properties", "override.properties"})
public class MyABProperties {
    ....
}
```

**Comment by azakordonets** [comment]
Now that's just awesome :) I love it, guys - thanks a lot
