### ISSUE TITLE
Without passing through -D, directly taking from System.

### ISSUE THREAD

**Issue by kpassoubady** [qatools/properties#41]
This is not an issue, just additional feature request:

Currently system variables are passed:

```
export property.name1=value1;
export property.name2=value2;

java -jar some.jar -Dproperty.name1=${property.name1} -Dproperty.name2=${property.name1} ...

```
While we want something like
```
export property.name1=value1;
export property.name2=value2;

# we want jar code to be aware about these settings

java -jar some.jar   
```

if the system environment variable declared with the property file
KEY=VALUE

can we take it without passing through -D.

Let me know whether you can implement it.

**Comment by baev** [comment]
@kpassoubady I guess you are talking about environment variables support, am I right?

**Comment by lanwen** [comment]
Simple example of own env provider:

https://github.com/yandex-qatools/juseppe/blob/master/src/main/java/ru/lanwen/jenkins/juseppe/props/Props.java#L26-L33

**Comment by baev** [comment]
@lanwen :+1: 

Maybe we should add `EnvVarPropertyLoader`?

**Comment by kpassoubady** [comment]
@baev Yes. We need to gather the property file Key,Value info, without passing through -D option.
Currently -D options works great, but when we have too many parameters it makes difficult to pass around.

**Comment by baev** [comment]
@kpassoubady as @lanwen mentioned before, you all you need is add the `PropertyProvider` like this: 
 
```java
PropertyLoader.newInstance().withPropertyProvider(new DefaultPropertyProvider() {
    @Override
    public Properties provide(ClassLoader classLoader, Class<?> beanClass) {
        Properties provided = super.provide(classLoader, beanClass);

        // Put env vars if absent
        Stream.of(JuseppeEnvVars.JuseppeEnvEnum.values())
                .forEach(env -> provided.computeIfAbsent(env.mapping(), key -> System.getenv(env.name())));

        return provided;
    }
}).populate(this);
```

**Comment by kpassoubady** [comment]
thanks :-)

**Comment by baev** [comment]
I guess I can close this one. If you have more questions feel free to ask
