### ISSUE TITLE
Can't override properties using gradle -D or -P options

### ISSUE THREAD

**Issue by ysparrow** [qatools/properties#44]
Using Maven I can override my properties by:

> mvn -Dmy.property=value

But with gradle property value is always taken from property file:

> gradlew -Dmy.property=value  
(the same for: gradlew -Pmy.property=value)

However, according to the:
https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties  
it should work the same way:

> The -D option of the gradle command has the same effect as the -D option of the java command.

**Comment by lanwen** [comment]
what the full command?

**Comment by ysparrow** [comment]
`gradlew -Dapp.default.url="http://mynewprog/app" test --tests tests.authentication.* `

test.properties file:
`app.default.url=http://myprog/app`

Reader class:
```
package framework;
import ru.qatools.properties.*;

@Resource.Classpath("test.properties")
public interface ConfigReader {

	@Property("app.default.url")
         String getDefaultAppUrl();
}

```

**Comment by lanwen** [comment]
please check is there System properties available with your changed value when populating class

**Comment by ysparrow** [comment]
Hi, sorry for the late response.

You are right System.properties are not available to application when run via gradle wrapper. It is available on gradle runner level, so you have to implicitly transfer it. 

I've add this code to my build.gradle and it works now when use -D option

```
test {
    if(System.getProperty("app.default.url")!=null)
    systemProperty "app.default.url", System.getProperty("app.default.url")
}

```

However this way brokes some magic of using properties library as it is for Maven by default. :)

Thank you. I close the issue.

**Comment by lanwen** [comment]
try this:

```
test {
     systemProperties System.properties
}
```

**Comment by ysparrow** [comment]
Thanks a lot! It works much better! I'm happy again )
